import { useState } from 'react';

export default function ShareButton({ songData, analysis }) {
  const [copied, setCopied] = useState(false);

  const handleShare = async () => {
    const text = `Check out what my photo sounds like! "${songData?.title || 'My Song'}" — generated by PhotoSound from a ${analysis?.genre || 'photo'}-style track.`;
    const url = typeof window !== 'undefined' ? window.location.origin : 'https://photosound.vercel.app';

    try {
      if (navigator.share) {
        await navigator.share({
          title: songData?.title || 'My PhotoSound Song',
          text,
          url,
        });
      } else {
        await navigator.clipboard.writeText(`${text}\n\n${url}`);
        setCopied(true);
        setTimeout(() => setCopied(false), 2500);
      }
    } catch (err) {
      // User cancelled share or clipboard failed silently
    }
  };

  return (
    <button
      onClick={handleShare}
      className="flex items-center gap-2 px-4 py-2 rounded-xl text-sm text-white/60 hover:text-white hover:bg-white/5 transition-all"
      aria-label="Share your song"
    >
      {copied ? (
        <>
          <svg className="w-4 h-4 text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
          </svg>
          <span className="text-green-400">Copied!</span>
        </>
      ) : (
        <>
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 13.003 9 12.632 9 12.25c0-.382-.114-.753-.326-1.053M15.684 13.342c.102.339.102.71 0 1.053M15.684 17.158C15.886 16.819 16 16.447 16 16.065c0-.382-.114-.753-.326-1.053M8.684 17.158c-.102.339-.102.71 0 1.053M12 10.75c0 1.035-.403 1.954-1.045 2.604L12 14l1.045-.646A2.5 2.5 0 0012 10.75zM12 21.75c0-.382-.114-.753-.326-1.053M12 24c.551 0 1-.449 1-1s-.449-1-1-1-1 .449-1 1 .449 1 1 1z" />
          </svg>
          Share
        </>
      )}
    </button>
  );
}